add all event attribute types
gunnarmorling/jfrunit pull request #23
Opened 2021-01-06 02:16 UTC by HashZhang

add all event attribute types

2021-01-06 20:05 UTC, gunnarmorling commented on src/main/java/dev/morling/jfrunit/ExpectedEvent.java
> +        else if (value instanceof Boolean) {
```suggestion
        else if (value instanceof Byte) {
```

2021-01-06 20:08 UTC, gunnarmorling requested changes
Thanks a lot! Two small comments inline. Can the value also be of a primitive type (e.g. `int` instead of `Integer`)? If so, this would need consideration too. And could you add some test too? Probably the easiest would be a custom event with one attribute of each type.

Lastly, could you author the commit with an email address associated to your GitHub account?

Thanks a lot!

2021-01-06 20:08 UTC, gunnarmorling commented on src/main/java/dev/morling/jfrunit/ExpectedEvent.java
>          // TODO all event attribute types
TODO comment is obsolete now.

2021-01-07 03:53 UTC, HashZhang commented
ok, thanks, will be done soon

2021-01-07 15:04 UTC, ebramirez commented on src/main/java/dev/morling/jfrunit/ExpectedEvent.java
> +        else if (value instanceof Byte) {
```suggestion
        else if (value instanceof Boolean) {
```

2021-01-08 03:06 UTC, HashZhang commented
I will open another pull request to add more rigorous logic.

2021-01-08 03:06 UTC, closed without merging